app:
  security:
    jwt:
      secret-key: "mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey"
      expiration-time: 300000 # 5 dəqiqə (milisaniyə ilə: 1000 * 60 * 5)
      refresh-expiration: 604800 # 7 gün saniyə ilə (Refresh Token üçün)